
const companies = [
  "Tata Consultancy Services",
  "Infosys",
  "Wipro",
  "HCL Technologies",
  "Tech Mahindra",
  "Larsen & Toubro Infotech",
  "Mindtree",
  "Capgemini India",
  "Accenture India",
  "IBM India",
  "Cognizant",
  "Amazon India",
  "Google India",
  "Microsoft India",
  "Flipkart",
  "Ola Cabs",
  "Uber India",
  "Paytm",
  "PhonePe",
  "Swiggy",
  "Zomato",
  "BYJU'S",
  "Unacademy",
  "Freshworks",
  "Zoho",
  "InMobi",
  "Delhivery",
  "Razorpay",
  "CRED",
  "Meesho",
  "Udaan",
  "Dream11",
  "Nykaa",
  "PolicyBazaar",
  "MakeMyTrip",
  "RedBus",
  "BigBasket",
  "Urban Company",
  "Lenskart",
  "OYO Rooms",
  "Quikr",
  "Snapdeal",
  "Myntra",
  "BookMyShow",
  "Cleartrip",
  "1mg",
  "CureFit",
  "Practo",
  "Dunzo",
  "Groww",
  "ShareChat",
  "Bounce",
  "Rivigo",
  "BlackBuck",
  "CarDekho",
  "Cars24",
  "NoBroker",
  "Housing.com",
  "Naukri.com",
  "Shiksha.com",
  "Times Internet",
  "HackerRank",
  "HackerEarth",
  "Turing",
  "UpGrad",
  "Vedantu",
  "WhiteHat Jr.",
  "Testbook",
  "Toppr",
  "Ernst & Young India",
  "Deloitte India",
  "KPMG India",
  "PwC India",
  "Siemens India",
  "Bosch India",
  "Honeywell India",
  "Samsung R&D India",
  "Nvidia India",
  "Intel India",
  "Qualcomm India",
  "Oracle India",
  "SAP Labs India",
  "Adobe India",
  "Salesforce India",
  "LinkedIn India",
  "Twitter India",
  "Facebook India",
  "Reliance Jio",
  "Bharti Airtel",
  "Vodafone Idea",
  "Tata Steel",
  "Tata Motors",
  "Mahindra & Mahindra",
  "Maruti Suzuki",
  "Hero MotoCorp",
  "Bajaj Auto",
  "TVS Motor",
  "Asian Paints",
  "Pidilite Industries",
  "Godrej Group",
  "Aditya Birla Group",
  "Hindustan Unilever",
  "ITC Limited",
  "Nestle India",
  "Britannia Industries",
  "Parle Products",
  "Amul",
  "Havells India",
  "Bharat Petroleum",
  "Indian Oil Corporation",
  "ONGC",
  "GAIL India",
  "NTPC Limited",
  "Coal India",
  "Power Grid Corporation",
  "Tata Power",
  "JSW Steel",
  "Vedanta Resources",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "State Bank of India",
  "Punjab National Bank",
  "Bank of Baroda",
  "IDFC FIRST Bank",
  "IndusInd Bank",
  "Yes Bank",
  "Canara Bank",
  "Union Bank of India",
  "Federal Bank",
  "South Indian Bank",
  "RBL Bank",
  "Bandhan Bank",
  "IDBI Bank",
  "LIC India",
  "Max Life Insurance",
  "Bajaj Finserv",
  "Muthoot Finance",
  "Manappuram Finance",
  "Tata AIA Life",
  "HDFC Life",
  "ICICI Prudential",
  "SBI Life Insurance",
  "Star Health Insurance",
  "Apollo Hospitals",
  "Fortis Healthcare",
  "Max Healthcare",
  "Sun Pharma",
  "Dr. Reddy's Laboratories",
  "Cipla",
  "Biocon",
  "Lupin Limited",
  "Aurobindo Pharma",
  "Cadila Healthcare",
  "Torrent Pharmaceuticals",
  "Glenmark Pharmaceuticals",
  "Wockhardt",
  "Sun TV Network",
  "Zee Entertainment",
  "Sony Pictures Networks India",
  "Network18",
  "Balaji Telefilms",
  "PVR Cinemas",
  "INOX Leisure",
  "Saregama India",
  "T-Series",
  "Red FM",
  "Radio Mirchi",
  "Dainik Bhaskar Group",
  "The Times Group",
  "Hindustan Times",
  "The Hindu Group",
  "Indian Express Group",
  "Jagran Prakashan",
  "ABP Group",
  "Amar Ujala",
  "DB Corp",
  "Future Group",
  "Reliance Retail",
  "Aditya Birla Fashion & Retail",
  "Shoppers Stop",
  "V-Mart Retail",
  "Spencer's Retail",
  "Trent Limited",
  "Raymond Group",
  "Arvind Limited",
  "Page Industries",
  "Bata India",
  "Relaxo Footwears",
  "Titan Company",
  "Tanishq",
  "BlueStone",
  "CaratLane",
  "FabIndia",
  "Pantaloons",
  "Westside",
  "Central",
  "Lifestyle",
  "Max Fashion",
  "Big Bazaar",
  "DMart",
  "Metro Cash & Carry",
  "Reliance Digital",
  "Croma",
  "Vijay Sales",
  "Sangeetha Mobiles",
  "Poorvika Mobiles",
  "Chroma",
  "SpiceJet",
  "IndiGo",
  "Air India",
  "Vistara",
  "Go First",
  "AirAsia India",
  "Jet Airways",
  "Indian Railways",
  "IRCTC",
  "Bharat Electronics",
  "Bharat Dynamics",
  "Hindustan Aeronautics",
  "BEML Limited",
  "Mazagon Dock Shipbuilders",
  "Garden Reach Shipbuilders",
  "Cochin Shipyard",
  "Bharat Forge",
  "Ashok Leyland",
  "Eicher Motors",
  "Force Motors",
  "Sundaram Clayton",
  "SKF India",
  "Timken India",
  "Schneider Electric India",
  "ABB India",
  "GE India",
  "Alstom India",
  "Hitachi India",
  "Jindal Steel & Power",
  "JSPL",
  "Essar Steel",
  "Bhushan Steel",
  "Tata Chemicals",
  "SRF Limited",
  "Gujarat Alkalies & Chemicals",
  "Pidilite Industries",
  "Berger Paints",
  "Kansai Nerolac Paints",
  "Shalimar Paints",
  "Asian Paints",
  "Berger Paints",
  "Nippon Paint India",
  "AkzoNobel India",
  "Grasim Industries",
  "UltraTech Cement",
  "Ambuja Cements",
  "ACC Limited",
  "Shree Cement",
  "Dalmia Bharat",
  "JK Cement",
  "Ramco Cements",
  "India Cements",
  "Birla Corporation",
  "HeidelbergCement India",
  "Orient Cement",
  "Prism Johnson",
  "Star Cement",
  "JK Lakshmi Cement",
  "Sagar Cements",
  "Mangalam Cement",
  "Kesoram Industries",
  "Chettinad Cement",
  "Penna Cement",
  "Zuari Cement",
  "Rain Industries",
  "Nuvoco Vistas",
  "Wonder Cement",
  "My Home Industries",
  "Anjani Portland Cement",
  "Deccan Cements",
  "HeidelbergCement India",
  "Sanghi Industries",
  "Shree Digvijay Cement",
  "Andhra Cements",
  "Burnpur Cement",
  "J K Cement",
  "JK Lakshmi Cement",
  "KCP Limited",
  "Orient Cement",
  "Sagar Cements",
  "Saurashtra Cement",
  "Shree Cement",
  "UltraTech Cement",
  "Vicat Sagar Cement",
  "Zuari Cement"
];


const jobLocations = [
  "Bengaluru, Karnataka",
  "Hyderabad, Telangana",
  "Pune, Maharashtra",
  "Gurugram, Haryana",
  "Noida, Uttar Pradesh",
  "Chennai, Tamil Nadu",
  "Mumbai, Maharashtra",
  "Kolkata, West Bengal",
  "Ahmedabad, Gujarat",
  "Delhi, Delhi",
  "Thiruvananthapuram, Kerala",
  "Kochi, Kerala",
  "Chandigarh, Chandigarh",
  "Indore, Madhya Pradesh",
  "Jaipur, Rajasthan",
  "Coimbatore, Tamil Nadu",
  "Visakhapatnam, Andhra Pradesh",
  "Nagpur, Maharashtra",
  "Lucknow, Uttar Pradesh",
  "Bhubaneswar, Odisha",
  "Vadodara, Gujarat",
  "Mysuru, Karnataka",
  "Surat, Gujarat",
  "Vijayawada, Andhra Pradesh",
  "Madurai, Tamil Nadu",
  "Patna, Bihar",
  "Bhopal, Madhya Pradesh",
  "Rajkot, Gujarat",
  "Kanpur, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Jamshedpur, Jharkhand",
  "Raipur, Chhattisgarh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Varanasi, Uttar Pradesh",
  "Aurangabad, Maharashtra",
  "Guwahati, Assam",
  "Dehradun, Uttarakhand",
  "Amritsar, Punjab",
  "Jodhpur, Rajasthan",
  "Ranchi, Jharkhand",
  "Greater Noida, Uttar Pradesh",
  "Faridabad, Haryana",
  "Ghaziabad, Uttar Pradesh",
  "Trichy, Tamil Nadu",
  "Hubli-Dharwad, Karnataka",
  "Salem, Tamil Nadu",
  "Warangal, Telangana",
  "Gwalior, Madhya Pradesh",
  "Meerut, Uttar Pradesh",
  "Jabalpur, Madhya Pradesh",
  "Tirupati, Andhra Pradesh",
  "Udaipur, Rajasthan",
  "Jalandhar, Punjab",
  "Siliguri, West Bengal",
  "Durgapur, West Bengal",
  "Vellore, Tamil Nadu",
  "Mangalore, Karnataka",
  "Kozhikode, Kerala",
  "Thrissur, Kerala",
  "Aligarh, Uttar Pradesh",
  "Bareilly, Uttar Pradesh",
  "Moradabad, Uttar Pradesh",
  "Solapur, Maharashtra",
  "Kolhapur, Maharashtra",
  "Guntur, Andhra Pradesh",
  "Asansol, West Bengal",
  "Dhanbad, Jharkhand",
  "Ajmer, Rajasthan",
  "Jamnagar, Gujarat",
  "Bhilai, Chhattisgarh",
  "Cuttack, Odisha",
  "Bilaspur, Chhattisgarh",
  "Panaji, Goa",
  "Shillong, Meghalaya",
  "Imphal, Manipur",
  "Aizawl, Mizoram",
  "Itanagar, Arunachal Pradesh",
  "Gangtok, Sikkim",
  "Port Blair, Andaman and Nicobar Islands"
];

export {jobLocations, companies};